need to update: Severity Code Description Project File Line Suppression State Details Error (active) CS0121 The call is ambiguous between the following methods or properties: 'ApplicantTypeManager.ToggleApplicantType(bool)' and 'ApplicantTypeManager.ToggleApplicantType(bool)' IPOPHLTrademark.Client D:\source\git-repos\trademark-0411\Client\Pages\Index.razor 787 Error CS0111 Type 'ApplicantTypeManager' already defines a member called 'ToggleApplicantType' with the same parameter types IPOPHLTrademark.Client D:\source\git-repos\trademark-0411\Client\Services\ApplicantTypeManager.cs 21 Active